# REST Client explained
# https://github.com/Huachao/vscode-restclient

# Base URL / develop
@base_url = http://localhost:3000
# Base URL / production

## Fetch a specific user by email
###
GET {{base_url}}/users/cslee0034@gmail.com

## Create a new user
###
POST {{base_url}}/users
Content-Type: application/json

{
  "email": "cslee0034@gmail.com",
  "address": {
    "country": "South Korea",
    "city": "Seoul",
    "district": "Gangnam"
  },
  "addressDetail": "..."
}